import { ImageValidationError, inspectImageBytes } from "./image.ts";

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

function decodeBase64(encoded: string): Uint8Array {
  const binary = atob(encoded);
  return Uint8Array.from(binary, (character) => character.charCodeAt(0));
}

// A complete 1x1 grayscale+alpha PNG: signature, CRC-checked IHDR/IDAT/IEND,
// and a real zlib-compressed scanline. A 24-byte header stub must not pass.
const VALID_ONE_PIXEL_PNG = decodeBase64(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAE0lEQVR4nGL4z8DwHwAAAP//AwAFAAH/d6oY3wAAAABJRU5ErkJggg==",
);

// A complete 1x1 baseline JPEG generated by macOS ImageIO. Its entropy-coded
// scan is decoded by ImageMagick-WASM, not merely accepted from SOF dimensions.
const VALID_ONE_PIXEL_JPEG = decodeBase64([
  "/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAA",
  "A6ABAAMAAAABAAEAAKACAAQAAAABAAAAAaADAAQAAAABAAAAAQAAAAD/7QA4UGhvdG9zaG9wIDMu",
  "MAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/8AAEQgAAQABAwEiAAIR",
  "AQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAAB",
  "fQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5",
  "OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeo",
  "qaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMB",
  "AQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYS",
  "QVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNU",
  "VVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5",
  "usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/bAEMAAgICAgICAwICAwUDAwMF",
  "BgUFBQUGCAYGBgYGCAoICAgICAgKCgoKCgoKCgwMDAwMDA4ODg4ODw8PDw8PDw8PD//bAEMBAgIC",
  "BAQEBwQEBxALCQsQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ",
  "EBAQEP/dAAQAAf/aAAwDAQACEQMRAD8A+L6KKK/lM/38P//Z",
].join(""));

// A complete still WebP encoded from the same real pixel fixture.
const VALID_ONE_PIXEL_WEBP = decodeBase64(
  "UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoBAAEAAgA0JaACdLoB+AADsAD+8MQL/yC5YXXI1/8gP+QH/ID/+PIAAAA=",
);

Deno.test("inspectImageBytes validates and decodes a complete PNG", async () => {
  const result = await inspectImageBytes(VALID_ONE_PIXEL_PNG);
  assert(result.mimeType === "image/png", "expected PNG MIME");
  assert(result.width === 1, "expected width 1");
  assert(result.height === 1, "expected height 1");
  assert(
    result.byteSize === VALID_ONE_PIXEL_PNG.byteLength,
    "expected exact byte size",
  );
  assert(/^[0-9a-f]{64}$/.test(result.checksumSha256), "expected SHA-256");
});

Deno.test("inspectImageBytes validates and decodes a complete JPEG", async () => {
  const result = await inspectImageBytes(VALID_ONE_PIXEL_JPEG);
  assert(result.mimeType === "image/jpeg", "expected JPEG MIME");
  assert(result.width === 1 && result.height === 1, "expected 1x1 dimensions");
  assert(
    result.byteSize === VALID_ONE_PIXEL_JPEG.byteLength,
    "expected exact byte size",
  );
});

Deno.test("inspectImageBytes validates and decodes a complete WebP", async () => {
  const result = await inspectImageBytes(VALID_ONE_PIXEL_WEBP);
  assert(result.mimeType === "image/webp", "expected WebP MIME");
  assert(result.width === 1 && result.height === 1, "expected 1x1 dimensions");
  assert(
    result.byteSize === VALID_ONE_PIXEL_WEBP.byteLength,
    "expected exact byte size",
  );
});

Deno.test("inspectImageBytes rejects a structurally truncated PNG", async () => {
  try {
    await inspectImageBytes(VALID_ONE_PIXEL_PNG.subarray(0, -1));
    throw new Error("expected validation failure");
  } catch (error) {
    assert(
      error instanceof ImageValidationError,
      "expected ImageValidationError",
    );
    assert(
      error.code === "png_chunk_invalid",
      "expected full-container validation",
    );
  }
});

Deno.test("inspectImageBytes rejects unsupported bytes deterministically", async () => {
  try {
    await inspectImageBytes(new Uint8Array([1, 2, 3, 4, 5]));
    throw new Error("expected validation failure");
  } catch (error) {
    assert(
      error instanceof ImageValidationError,
      "expected ImageValidationError",
    );
    assert(
      error.code === "image_magic_unsupported",
      "expected stable reason code",
    );
  }
});
