package com.gallr.app.share

private const val EXHIBITION_PAGE_BASE = "https://gallrmap.com/exhibitions/"
private val NON_SLUG_CHARACTERS = Regex("[^\\p{L}\\p{N}-]+")
private val WHITESPACE = Regex("\\s+")
private val REPEATED_HYPHENS = Regex("-+")

/** Unicode NFKC normalization (String.prototype.normalize("NFKC") on the web). */
internal expect fun normalizeNfkc(text: String): String

/** Port of web/scripts/lib/slug.js `slugify`; Korean and other scripts are kept as-is. */
fun slugifyForWeb(input: String): String {
    if (input.isEmpty()) return ""
    return normalizeNfkc(input.lowercase())
        .replace(NON_SLUG_CHARACTERS, " ")
        .trim()
        .replace(WHITESPACE, "-")
        .replace(REPEATED_HYPHENS, "-")
}

/** Port of web/scripts/lib/slug.js `buildSlug`. */
fun exhibitionWebSlug(
    nameEn: String,
    nameKo: String,
    id: String,
): String {
    val base = slugifyForWeb(nameEn.ifEmpty { nameKo })
    val suffix = id.take(4)
    return if (base.isEmpty()) suffix else "$base-$suffix"
}

/** Public exhibition page generated by the Eleventy build (web/exhibitions/exhibition.njk). */
fun exhibitionWebUrl(
    nameEn: String,
    nameKo: String,
    id: String,
): String = "$EXHIBITION_PAGE_BASE${exhibitionWebSlug(nameEn, nameKo, id)}/"
