// Converts `supabase db query ... -f export.sql` JSON output into the commonTest fixture source.
// Usage: node to-kotlin.mjs export.json > PublishedCatalogueFixture.kt
import { readFileSync } from "node:fs";

const input = JSON.parse(readFileSync(process.argv[2], "utf8"));
const rows = Array.isArray(input) ? input : input.rows;
if (!Array.isArray(rows) || rows.length === 0) throw new Error("expected a non-empty rows array");

// Kotlin raw strings cannot contain `"""`; `$` must be escaped as ${'$'}.
const literal = (row) => {
  const json = JSON.stringify(row);
  if (json.includes('"""')) throw new Error(`row ${row.id} contains a triple quote`);
  if (Buffer.byteLength(json, "utf8") > 60000) throw new Error(`row ${row.id} exceeds the constant size budget`);
  return '"""' + json.replaceAll("$", "${'$'}") + '"""';
};

const body = rows.map((row) => `            ${literal(row)},`).join("\n");
process.stdout.write(`// GENERATED by specs/088-discovery-accuracy-fixes/fixture/to-kotlin.mjs from export.sql.
// Public catalogue snapshot, reference date 2026-10-02. Do not edit by hand.
@file:Suppress("ktlint:standard:max-line-length")

package com.gallr.shared.fixture

internal object PublishedCatalogueFixture {
    val referenceDate: kotlinx.datetime.LocalDate = kotlinx.datetime.LocalDate(2026, 10, 2)

    val rowsJson: List<String> =
        listOf(
${body}
        )
}
`);
